# Generated by Django 4.2.1 on 2023-06-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0003_planes_alter_memorial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
