# Generated by Django 4.2.1 on 2023-06-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0004_planes_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='valor_factor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
