# Generated by Django 4.2.1 on 2023-06-16 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0004_familiares'),
    ]

    operations = [
    ]
