# Generated by Django 4.2.1 on 2023-06-16 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0005_auto_20230615_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='dv_familiar',
            field=models.CharField(default=0, max_length=1, validators=[django.core.validators.MaxLengthValidator(1)]),
        ),
        migrations.AddField(
            model_name='familiares',
            name='nacionalidad',
            field=models.CharField(choices=[('AR', 'Argentina'), ('BO', 'Bolivia'), ('BR', 'Brasil'), ('CL', 'Chile'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('EC', 'Ecuador'), ('SV', 'El Salvador'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('MX', 'México'), ('NI', 'Nicaragua'), ('PA', 'Panamá'), ('PY', 'Paraguay'), ('PE', 'Perú'), ('PR', 'Puerto Rico'), ('DO', 'República Dominicana'), ('UY', 'Uruguay'), ('VE', 'Venezuela'), ('OT', 'Otra')], default='CL', max_length=2),
        ),
        migrations.AddField(
            model_name='familiares',
            name='rut_familiar',
            field=models.CharField(default=12345678, max_length=8, validators=[django.core.validators.MaxLengthValidator(8)]),
        ),
    ]
