# Generated by Django 4.2.1 on 2023-06-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0007_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recuerdos',
            fields=[
                ('id_recuerdo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_recuerdo', models.TextField()),
            ],
        ),
    ]
