# Generated by Django 4.2.1 on 2023-06-16 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0008_recuerdos'),
    ]

    operations = [
        migrations.AddField(
            model_name='recuerdos',
            name='nombre_recuerdo',
            field=models.CharField(default='Nombre Recuerdo', max_length=100),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=128)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoria.roles')),
            ],
        ),
    ]
