# Generated by Django 4.2.1 on 2023-06-16 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0009_recuerdos_nombre_recuerdo_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios_Planes',
            fields=[
                ('id_plan_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoria.planes')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoria.usuarios')),
            ],
        ),
    ]
