# Generated by Django 4.2.1 on 2023-06-16 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0010_usuarios_planes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios_Planes',
        ),
    ]
