# Generated by Django 4.2.1 on 2023-06-16 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0005_planes_valor_factor'),
        ('memoria', '0012_usuarios_planes'),
    ]

    operations = [
    ]
