# Generated by Django 4.2.1 on 2023-06-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0013_merge_0005_planes_valor_factor_0012_usuarios_planes'),
    ]

    operations = [
    ]
