# Generated by Django 4.2.1 on 2023-06-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0014_auto_20230616_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios_planes',
            name='estado_plan',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
