# Generated by Django 4.2.1 on 2023-06-26 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memoria', '0015_usuarios_planes_estado_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios_planes',
            name='estado_plan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuarios_planes',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
