# Generated by Django 4.2.1 on 2023-06-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0016_alter_usuarios_planes_estado_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios_planes',
            name='estado_plan',
            field=models.IntegerField(),
        ),
    ]
