# Generated by Django 4.2.1 on 2023-06-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0017_alter_usuarios_planes_estado_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios_planes',
            name='estado_plan',
        ),
        migrations.AddField(
            model_name='usuarios_planes',
            name='estado',
            field=models.IntegerField(default=0),
        ),
    ]
