# Generated by Django 4.2.2 on 2023-06-27 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memoria', '0018_remove_usuarios_planes_estado_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiares',
            name='dv_familiar',
        ),
        migrations.RemoveField(
            model_name='familiares',
            name='rut_familiar',
        ),
        migrations.AddField(
            model_name='familiares',
            name='parentezco',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familiares',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
