# Generated by Django 4.2.1 on 2023-06-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0019_remove_familiares_dv_familiar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='link_pago',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
