# Generated by Django 4.2.1 on 2023-06-29 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0020_planes_link_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios_planes',
            name='fecha_act',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
